### PR TITLE
Add use 3 columns format translation image to README.md

### PR DESCRIPTION
**Pull request by fbukevin**
For better understanding and finding the item to turn on, adding the screenshot for this item.
old-column-format-translation

### CODE REVIEW

**Comment by DominikDoom** [comment]
A comparable image already exists in the [settings section](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete#%EF%B8%8F-settings) > Translation settings, so I don't think this is necessary. The switch is mentioned by name in the translation section, so a user could either scroll up and read the settings info or search the webui settings page for it directly.

**Comment by DominikDoom** [comment]
I guess that's fair, I can make it a bit clearer that this is a setting and where to find it.

What do you think of this phrasing, using your path example?

> This file needs to be a CSV in the format `<English tag/alias>,<Translation>`. Some older files use a three column format, which requires a compatibility setting to be activated.
> You can find it under `Settings > Tag autocomplete > Translation filename > Translation file uses old 3-column translation format instead of the new 2-column one`.
> With it on, the second column will be unused and skipped during parsing.

**Comment by fbukevin** [comment]
It looks good to me. I believe it is clear to quickly find the option.

**Comment by DominikDoom** [comment]
Alright, I added it in. Thanks for your suggestions.

**Pull request closed without merging**
