### PR TITLE
add support for hypernetworks and lora

### PR DESCRIPTION
**Pull request by Mulet-J**
Add hypernetworks and lora support using respectively "<h:" and "<l:".
Also change the embeddings access with "<e:".
This is working, but isn't finished.
Mostly adapted from the embeddings implementation.

I'm not very experienced, so this is pretty dirty overall.
Hope you can make some use of this.

### CODE REVIEW

**Comment by DominikDoom** [comment]
I was thinking about implementing pretty much exactly this, thanks a lot!

I'll definitely be able to use it from a quick glance, like you said there are a few things to add and clean up but it's a great start. I won't pretend my own code is clean either, so don't worry about that.

**Comment by DominikDoom** [comment]
Thanks again for your initial version, it was a great start to finish this up quickly.

I cleaned up the loading a bit since some stuff such as version info is only applicable to embeddings, so it could be simplified in a few places.
Other than that, the biggest change is that just `<` will now show all three types mixed for convenience, while still keeping the `<:e`, `<:h` or `<:l` notation if the user wants to filter based on the type. It also properly shows the gray meta text now to differentiate them, and uses the settings value for the multiplier on completion.

**Comment by CortesJoan** [comment]
So is the Lora support implemented in the main branch or not? Because, if it is, doesn't work for me. <l is still showing embeddings

**Comment by DominikDoom** [comment]
@CortesJoan It is. Just < will show all together, while <e:, <l: , <h: or the longer forms <lora: and <hypernet: will show only those. The : is important, else it will just search for entries containing l or h from all three, which might be what happened in your case.

**Comment by CortesJoan** [comment]
@DominikDoom I'm stupid I didn't see the : , thanks for the answer

**Pull request merged**
