### PR TITLE
Some performance optimizations

### PR DESCRIPTION
**Pull request by sgmklp**
There are four major changes to this branch:
1.The logic when adding the element of the result list is not very clear. I have made it clearer and the function is the same as before.
2.When the number of results is too large, the selection of results will not be smooth. I solved this problem using indexes. (Because only one result will be selected, there is no need to use a loop)
3.Change the global variables not defined by var to var, so as to use the "Go to Definition" function of IDE such as VS CODE.
4.When the number of results is too large, it took too long to load the result list. At first, only part of the results will be loaded, and then part of the results will be loaded when the last result is reached.The config option `resultStepLength` can set the number of everytime load.

### CODE REVIEW

**Comment by sgmklp** [comment]
Only see the last five commits, I started to modify it from there.

**Review by DominikDoom — CHANGES_REQUESTED** [review]
I like it and haven't found any issues. Just some small suggestions for code style / readability.

**Comment by sgmklp** [comment]
Well, I will follow these suggestions in my future work

**Comment by DominikDoom** [comment]
Alright, thanks for your hard work!
By the way just for the future, I would suggest using feature branches that just contain the new commits or newly setting up the dev branch, so that the old commits aren't included anymore. Just to make it easier to read and merge without squashing.

**Pull request merged**
